# Generated by Django 5.2.1 on 2025-06-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('bias', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Left'), (2, 'Centre Left'), (3, 'Centre Right'), (4, 'Right')])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('urlToImage', models.URLField(unique=True)),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApp.source')),
            ],
        ),
    ]
