# Generated by Django 5.2.1 on 2025-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='processed_title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
