# Generated by Django 5.2.1 on 2025-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_article_auto_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auto_topic',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
