# Generated by Django 5.2.1 on 2025-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_remove_article_auto_topic_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='bias',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Far Left'), (2, 'Left'), (3, 'Centre Left'), (4, 'Centre'), (5, 'Centre Right'), (6, 'Right'), (7, 'Far Right')]),
        ),
    ]
