# Generated by Django 5.2.1 on 2025-06-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_alter_source_bias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchMetadata',
        ),
    ]
