# Generated by Django 5.2.1 on 2025-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_delete_fetchmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
